<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <PackageId>Singulink.FulcrumFS.Videos</PackageId>
    <Description>
      FulcrumFS extension that adds customizable video processing capabilities, including validation, thumbnail generation, resizing, format conversion,
      metadata stripping, bitrate limiting, and audio stripping, for both original videos and their derived variants.
    </Description>
    <PackageTags></PackageTags>

    <!-- Handling for special custom hwaccel config mode -->
    <DefineConstants Condition=" '$(HWACCEL_MODE)' != '' ">$(DefineConstants);CUSTOM_HWACCEL_MODE</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'none' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_NONE</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'decodeonly' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_DECODEONLY</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'videotoolbox' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_VIDEOTOOLBOX</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'cuda' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_CUDA</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'qsv' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_QSV</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'amf' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_AMF</DefineConstants>
    <DefineConstants Condition=" '$(HWACCEL_MODE)' == 'd3d12va' ">$(DefineConstants);CUSTOM_HWACCEL_MODE_D3D12VA</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FulcrumFS\FulcrumFS.csproj" />

    <!-- Analyzers -->
    <PackageReference Include="hamarb123.Analyzers" PrivateAssets="All" />
  </ItemGroup>

</Project>
